### ISSUE TITLE
MySQL Client Error

### ISSUE THREAD

**Issue by gnobre** [retrievercommunications/docker-jasperserver#18] opened 2018-04-24 13:30 UTC
I'm simply trying to run jasperserver:

`docker-compose up`

but then the build fails and I get the following error:

`Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Client does not support authentication protocol requested by server; consider upgrading MySQL client`

I've tried to run with the command line as well and got the same error.

EDIT: I've just tried to run with postgres as the database, following [these instructions in another issue](https://github.com/retrievercommunications/docker-jasperserver/issues/10#issuecomment-341320324) and it worked fine

**Comment by grange74** [comment] 2018-04-25 04:58
Sorry it seems like the problem is caused by the new release of MySQL 8 and the fact that the docker-compose file in this report doesn't specify a version tag for the mysql image, so it gets whatever has the 'latest' tag. It really should have a specific version to avoid these problems. 
To fix this temporarily, add a version tag for a 5.X version of MySQL, E.g. :5.7 to image: mysql line. The same should work from the command line.

**Comment by grange74** [comment] 2018-04-25 05:01
So for the command line try:
```
docker run -d --name jasperserver_mysql -e MYSQL_ROOT_PASSWORD=mysql mysql:5.7
```

**Comment by grange74** [comment] 2018-04-25 05:02
And for the docker-compose.yml:
```
version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
```

**Comment by gnobre** [comment] 2018-04-25 17:13
Thanks @grange74, I actually haven't tried that, for now I'm using postgres and it's working fine :)

**Comment by grange74** [comment] 2018-05-28 20:57
Fixed in https://github.com/retrievercommunications/docker-jasperserver/pull/19. I will create a separate issue for supporting mysql 8.

Please note that if you get this error, you will need to atleast:

- delete the current mysql 8 container
- delete the data_dir (if you don't do this you will get another set of errors include [ERROR] [FATAL] Innodb: Table flags are 0...)
- create the new mysql 5.7 container

**Closed by grange74** 2018-05-28 20:57 UTC
